kind: pipeline
name: default

auth: &auth
    username:
        from_secret: dockerhub_username
    password:
        from_secret: dockerhub_password

repo: &repo
    repo: maxkratz/imapgrab

steps:
  - name: build-testing
    image: plugins/docker
    settings:
      <<: *repo
      tags: testing
      <<: *auth
    when:
      branch:
        exclude:
        - main
  - name: build-latest
    image: plugins/docker
    settings:
      <<: *repo
      tags: latest
      <<: *auth
    when:
      branch:
        - main
